### PR TITLE
vocore2: add switch config in mt7628 section

### PR DESCRIPTION
**Pull request by stargieg**

### CODE REVIEW

**Comment by noblepepper** [comment]
Thanks, I'm trying to duplicate all the changes I made in my chaos calmer repo. I haven't been spending as much time as I would like on this so progress has been slow.

Fixes for other issues or missing items is appreciated!

**Comment by stargieg** [comment]
What is required for sound output on lede with kernel 4.4 ? Or should it work? I have kmod-sound-mt7620 installed and no PCM dev.

**Comment by noblepepper** [comment]
I think these are all the related changes to [chaos calmer](https://github.com/noblepepper/openwrt-chaoscalmer) (3.18 kernel), similar will be needed for lede and OpenWrt trunk (4.4 kernels). There is a lot of repetition in these, changing, unchanging, rechanging the same files so expect to be confused some. My Chaos Calmer repo is a mess.

The biggest part of getting sound will be sorting out my poor housekeeping and getting the modules to compile for 4.4 kernels.

I am intentionally keeping the sound work separate for a few reasons a big one is I'm not sure the lede developers will accept some things and It may end up in the [feed].(https://github.com/noblepepper/VoCore2-lede-feed) I think the driver you have compiled has been [dropped](https://github.com/openwrt/openwrt/commit/547b4b0a3943dc4992b8a3ef7116a36710c62b0d)

commit 6d13e71917a7c6ccb44e64981da65df10b3e0684
Author: Noble Pepper <openwrtmail@noblepepper.com>
Date:   Sun Nov 20 13:14:44 2016 -0600

    Change dts for es8388 codec

commit f90c7a2a46989e66d99df2ed09e23d7734133e2f
Author: Noble Pepper <openwrtmail@noblepepper.com>
Date:   Sun Nov 20 08:32:52 2016 -0600

    Set module load order

commit 006e51afcf9f43416410113f898a88c4cbb5d253
Author: Noble Pepper <openwrtmail@noblepepper.com>
Date:   Sun Nov 20 08:25:50 2016 -0600

    rename es8388 patch

commit d52667a66bf5b2023ca733e2171a8c3447c56ed2
Author: Noble Pepper <openwrtmail@noblepepper.com>
Date:   Mon Nov 14 13:33:13 2016 -0600

    switch to Vongers es8388 patch

commit 0dc7bc812d03669d775a0241a4c3f160f7f6e6a7
Author: Noble Pepper <openwrtmail@noblepepper.com>
Date:   Mon Nov 14 13:18:37 2016 -0600

    remove broken alsa driver


commit 51662f6a57453a24f631910884ac1cb76d9cf6fd
Author: Noble Pepper <openwrtmail@noblepepper.com>
Date:   Fri Nov 11 15:10:11 2016 -0600

    fix mt7628 audio setup

commit 3fc3a136e9249d94fc77afc96fb23f85c51e587d
Author: Noble Pepper <openwrtmail@noblepepper.com>
Date:   Thu Nov 10 13:05:10 2016 -0600

    package alsa driver and es8388 codec driver

commit 41ddf1dd4775036191aad72f3258908ed4f06a87
Author: Noble Pepper <openwrtmail@noblepepper.com>
Date:   Thu Nov 10 13:03:18 2016 -0600

    Add es8388 codec driver, update mt7628 alsa driver, remove nonworking
    alsa driver

**Comment by stargieg** [comment]
THX
I will try to get the sound working.
>I am intentionally keeping the sound work separate for a few reasons a big one is I'm not sure the lede developers will accept some things and It may end up in the [feed]

Which feed do you mean? The link is broken.

**Comment by noblepepper** [comment]
Sorry, misplaced "."  Try this, https://github.com/noblepepper/VoCore2-lede-feed if that doesn't work just look for VoCore2-lede-feed in my list of repos. 

You need this in feeds.conf.default to enable it `src-git VoCore2 https://github.com/noblepepper/VoCore2-lede-feed` and do `./scripts/feeds update -a;./scripts/feeds install -a;rm -rf tmp` before you run make menuconfig.

**Pull request merged**
